Module7 task1
htmlacademy-php1/321199-yeticave-13 pull request #18
Opened 2021-09-01 22:26 UTC by Kenny201

Регистрация на сайте

2021-09-02 04:10 UTC, mihan007 requested changes
Слушай, я не понимаю почему в этом PR мы решаем задачу добавления лота? У нас же регистрация на сайте https://up.htmlacademy.ru/php/13/check/tasks/321199/14? И бот в описании PR это написал.

2021-09-02 04:10 UTC, mihan007 commented on add.php
> +    require_once('bootstrap.php');
откуда тут отступ всего кода? не нужно

2021-09-02 04:10 UTC, mihan007 commented on add.php
> +    if ($_SERVER['REQUEST_METHOD'] == 'POST') {
делаем отдельный файл и выносим туда всю логику проверки. на выходе этого файла будет функция, которую ты будешь вызывать и передавать внутрь данные формы

2021-09-10 10:55 UTC, runtothefather requested changes

2021-09-10 10:55 UTC, runtothefather commented on functions/routes.php
> +        return (count($params) > 0) ? $url . '?' . $params[0] . '=' . $params[1] : $url;
https://www.php.net/manual/en/function.http-build-query.php
уже всё придумано раньше лучше использовать вот эту функцию а не писать свою, к тому же эта не умеет работать с несколькими параметрами

2021-09-10 10:55 UTC, runtothefather commented on functions/validate.php
> +        $text = xssAdg($_POST[$title]);
чистить данные не задача валидации

2021-09-10 10:55 UTC, runtothefather commented on functions/validate.php
> +        $text = xssAdg($_POST[$title]);
можно пока оставить

2021-09-10 10:55 UTC, runtothefather commented on functions/validate.php
> +        if ($post_date) {
что здесь ожидается null? пустая строка. и тд, лучше делать максимально строгие сравнения - $post_date !== null например

2021-09-10 10:55 UTC, runtothefather commented on functions/validate.php
> +            if ($date_time_format < $date_valide_format) {
DateTime объекты можно сравнивать

2021-09-10 10:55 UTC, runtothefather commented on functions/validate.php
> +            if ($date_time_format !== $post_date) {
формат так не проверишь, если нужно проверить формат то используй регулярные выражения

2021-09-10 10:55 UTC, runtothefather commented on functions/validate.php
> +        if (!$_POST[$title]) {
isset? null === ? условия должны быть понятными что там ожидается

2021-09-10 10:55 UTC, runtothefather commented on add.php
> +<?php
добавить везде типы аргументов и типы возвращаемых значений из функций

2021-09-10 10:55 UTC, runtothefather commented on db/db_add_lot.php
> +        $stmt->bind_param("siidssis", $_POST['lot-name'],$user_id, $_POST['category'], $_POST['lot-rate'], $img_title, $_POST['message'], $_POST['lot-step'], $_POST['lot-date']);
данные из пост нужно обработать сначала, заэкранировать и тд, нельзя пользовательский инпут сразу писать в запрос в бд

2021-09-12 14:29 UTC, runtothefather approved these changes

2021-09-12 14:29 UTC, merged