Добавил вывод массивов товаров и категорий через циклы
htmlacademy-php1/321199-yeticave-13 pull request #4
Opened 2021-07-21 17:39 UTC by Kenny201

2021-07-21 18:21 UTC, mihan007 requested changes
1. Поправь момент с упрощением isset
2. Настрой в ide psr-12 и выполни в отдельном PR автоформатирование всего проекта. Сейчас в diff у тебя попадают и строки кода с заданием, и результат переформатирования. Это неудобно, принято только целевой код видеть. Это достигается единым CodeStyle

2021-07-21 18:21 UTC, mihan007 commented on index.php
> +                            <?=$ad['category']?>
В простых случаях используй $a ?? ''. isset очень редко нужен. Остальные места посмотри, пожалуйста.

2021-07-21 20:00 UTC, Kenny201 commented
Напортачил маленько, извиняюсь, но всё поправил

2021-07-22 04:53 UTC, mihan007 requested changes

2021-07-22 04:53 UTC, mihan007 commented on index.php
> +<<<<<<< HEAD
чот ты смерджил вообще не как надо. у тебя сейчас служебные `<<<<<<< HEAD` и др - это следы незаконченного мерджа

2021-07-22 04:53 UTC, mihan007 commented
@Kenny201 не все поправил, надо еще)

2021-07-22 05:09 UTC, Kenny201 commented
Сейчас ок?)

2021-07-22 18:29 UTC, closed without merging