Перенёс массивы и функцию в отдельные файлы, создал шаблоны layout и …
htmlacademy-php1/321199-yeticave-13 pull request #9
Opened 2021-07-28 20:28 UTC by Kenny201

Перенёс массивы и функцию в отдельные файлы, создал шаблоны layout и main, подключил их в index. Добавил фильтрацию от html, js тегов.

2021-07-29 05:44 UTC, mihan007 requested changes
Классная работа! Видно, что в теме хорошо разобрался.

1. Смотри - некоторые замечания исключительно по code style. Казалось бы, неважные мелочи, но, на самом деле, важно их проработать на начальном этапе и к ним потом не возвращаться.
2. Момент важнее - это фильтрация данных и защита от xss атак. Обычно применяется просто htmlspecialchars, так как он не калечит строку, а просто делает ее безопасной к выводу. 
Сравним. Есть текст `<b>a=1</b>`. strip_tags от нее оставит `a=1`. А вот htmlspecialchars просто заменит `<` на `&lt;` и `>` на `&gt;`. То есть на выводе пользователь увидит прям то, что ввел `<b>a=1</b>` и при этом данный ввод не повлияет на нормальную работу. Посмотри на эту функцию внимательнее, она лучше всего подходид на экранирование данных

2021-07-29 05:44 UTC, mihan007 commented on index.php
> +$main = include_template('main.php', ['categories' => $categories, 'advertisement' => $advertisement]);
попробуй тут функцию `compact` для параметров

2021-07-29 05:44 UTC, mihan007 commented on index.php
> +        "user_name" => $user_name,
единый стиль кавычек приятнее для глаза и в работе. пожалуй, тут одинарные везде надо

2021-07-29 05:44 UTC, mihan007 commented on templates/main.php
> +                <a class="promo__link" href="pages/all-lots.html"><?= strip_tags($category) ?></a>
также нужен https://www.php.net/manual/ru/function.htmlspecialchars.php здесь и далее эффективнее справляется и меньше калечит входную строку. 

советую экранирование переменных выделить в отдельную функцию с простым именем, например, `function e($str)` и везде ее использовать. тогда алгоритм очистки данных перед выводом будет в одной функции и мы сможем его менять по мере изучения технологии защиты.

https://qna.habr.com/q/11169

2021-07-29 05:44 UTC, mihan007 commented on db.php
> +    ["name" => 'Маска Oakley Canopy', "category" => 'Разное', "price" => '5400', "img" => 'img/lot-6.jpg']
лучше единообразно. у тебя остальные элементы массива отформатированы в столбик. если здесь сделать аналогично, то получится красиво и легче для восприятия

2021-07-30 04:04 UTC, mihan007 approved these changes
Браво!

2021-07-30 04:04 UTC, merged

2021-07-30 05:45 UTC, Kenny201 commented
😄